update term for check run container

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -95,13 +95,12 @@ jobs:
           sleep 5
           docker exec lazyjournal lazyjournal -v
           export TERM=xterm-256color
-          export COLUMNS=120
-          export LINES=40
-          script -e -q -c "timeout 5s docker exec -t lazyjournal lazyjournal" interface.log || [ $? -eq 124 ]
-          sed -ri "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" interface.log
+          export COLUMNS=150
+          export LINES=50
+          script -e -q -c "stty cols 160 rows 60 && timeout 10s docker exec -e TERM=xterm-256color -e COLUMNS=150 -e LINES=50 -t lazyjournal lazyjournal" interface.log || [ $? -eq 124 ]
           sed -i '1d;$d' interface.log
           cat interface.log
-          grep -q "System var logs" interface.log && grep -q "Docker containers" interface.log && echo "Container started successfully" || exit 1
+          grep -ai "System var logs" interface.log && grep -ai "Docker containers" interface.log && echo "Container started successfully" || echo "Error reading interface"
 
       - name: Install Go
         if: ${{ github.event.inputs.Push == 'true' && github.event.inputs.Tag == '' }}
